run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign

issues:
  exclude-rules:
    - path: server/storage/store.go
      linters:
        - typecheck