name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install build dependencies
      working-directory: sdk/python
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      working-directory: sdk/python
      run: python -m build
      
    - name: Publish to PyPI
      working-directory: sdk/python
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Publishing to Test PyPI for manual trigger"
          python -m twine upload --repository testpypi dist/*
        else
          echo "Publishing to PyPI for tag release"
          python -m twine upload dist/*
        fi

